version: "3"

vars:
  GITUSER:
    sh: git config user.name || echo "Unknown User"

dotenv:
  - .env

tasks:
  check:
    desc: Check django app for errors
    cmd: uv run python manage.py check

  run:
    desc: Runs the Django app in production mode
    deps:
      - install
    env:
      DJANGO_DEBUG: 0
    cmds:
      - pnpm run build:ts
      - uv run python manage.py collectstatic --noinput --clear
      - uv run python manage.py runserver

  install:
    desc: Meta task to install all dependencies and packages
    deps:
      - python:install-dependencies
      - javascript:install-dependencies

  python:install-dependencies:
    desc: Install Python dependencies and packages
    sources:
      - pyproject.toml
      - uv.lock
    generates:
      - .venv/
    cmds:
      - uv sync

  javascript:install-dependencies:
    desc: Install NodeJS dependencies and packages
    sources:
      - package.json
    generates:
      - pnpm-lock.yaml
      - node_modules/
    cmds:
      - pnpm i --frozen-lockfile
  
  javascript:compile:
    desc: Compile TypeScript into JavaScript
    cmds:
      - pnpm run build:ts

  django:create-migrations:
    desc: Create missing Django migration files
    cmds:
      - uv run python manage.py makemigrations
  
  django:run-migrations:
    desc: Apply Django database migrations
    cmds:
      - uv run python manage.py migrate

  clean:
    desc: Cleans up Python bytecode, .venv and node_modules
    cmds:
      - py3clean .
      - rm -rf node_modules/
      - rm -rf .venv/

  setup:
    desc: Set up the project for local development, including migration generation
    cmds:
      - task: install
      - task: javascript:compile
      - task: django:create-migrations
      - task: django:run-migrations
      - task: check

  manage:sync_players:
    desc: Run python manage.py sync_players
    cmd: uv run python manage.py sync_players
  