version: "3"

vars:
  GITUSER:
    sh: git config user.name || echo "Unknown User"

tasks:
  check:
    desc: Check django app for errors
    cmd: uv run python manage.py check

  install:
    deps:
      - install-python-dependencies
      - install-js-dependencies

  install-python-dependencies:
    desc: Install Python dependencies and packages
    sources:
      - pyproject.toml
      - uv.lock
    generates:
      - .venv/pyvenv.cfg
    cmds:
      - uv sync

  install-js-dependencies:
    desc: Install NodeJS dependencies and packages
    sources:
      - packages.json
    generates:
      - package-lock.json
    cmds:
      - npm install

  create-migrations:
    desc: Create django migrations
    cmds:
      - uv run python manage.py makemigrations
