# Generated by Django 6.0.5 on 2026-05-25 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingame_name', models.CharField(max_length=100, unique=True)),
                ('alliance_rank', models.CharField(choices=[('R1', 'R1'), ('R2', 'R2'), ('R3', 'R3'), ('R4', 'R4'), ('R5', 'R5')], default='R1', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('can_be_conductor', models.BooleanField(db_index=True, default=True, help_text='Whether this player should be considered for train conductor rotation.')),
                ('can_be_vip', models.BooleanField(db_index=True, default=True, help_text='Whether this player can be selected as VIP / Guardian Defender.')),
                ('reliability_score', models.PositiveSmallIntegerField(default=3, help_text='Manual score from 1 to 5. Higher means more reliable.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('last_conductor_at', models.DateField(blank=True, null=True)),
                ('last_vip_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ingame_name'],
            },
        ),
    ]
