# Generated by Django 6.0.5 on 2026-05-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
