# Generated by Django 6.0.5 on 2026-07-14 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_storedimage_imageattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainrotationentry',
            options={'ordering': ['position', 'player__ingame_name'], 'permissions': [('manage_train_rotation', 'Can add, remove, and reorder train rotation entries')], 'verbose_name': 'train rotation entry', 'verbose_name_plural': 'train rotation entries'},
        ),
    ]
