# Generated by Django 6.0.5 on 2026-06-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comment_deleted_at_comment_deleted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('joined_count', models.PositiveIntegerField(default=0)),
                ('left_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Player sync run',
                'verbose_name_plural': 'Player sync runs',
                'ordering': ['-started_at'],
            },
        ),
    ]
