x-container-hardening: &container-hardening
  read_only: true
  tmpfs:
    - /tmp:rw,noexec,nosuid,size=64m
    - /run:rw,noexec,nosuid,size=16m
    - /home/django:rw,noexec,nosuid,size=16m
  security_opt:
    - no-new-privileges:true
  cap_drop:
    - ALL

services:
  management:
    image: ghcr.io/271u/train-conductors:v0.0.1-alpha3
    restart: unless-stopped
    <<: *container-hardening
    volumes:
      - ./data:/app/data:rw
    networks:
      - internal
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.trains-preprod.rule=Host(`trains.2271-united.org`)
      - traefik.http.routers.trains-preprod.entrypoints=https
      - traefik.http.routers.trains-preprod.tls=true
      - traefik.http.routers.trains-preprod.tls.certresolver=letsencrypt
      - traefik.http.services.trains-preprod.loadbalancer.server.port=8000


  player-sync:
    image: ghcr.io/271u/train-conductors:v0.0.1-alpha3
    restart: unless-stopped
    command: ["sh", "/app/scripts/run_player_sync_periodically.sh"]
    volumes:
      - ./data:/data
    environment:
      <<: *train-conductors-environment
    depends_on:
      - train-conductors
    networks:
      - internal


networks:
  internal:
  traefik-public:
    external: true
